# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_and_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('status', models.CharField(max_length=1)),
                ('appt_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='login_and_registration_app.User')),
            ],
        ),
    ]
