# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('description', models.TextField(max_length=100)),
                ('weight', models.CharField(max_length=42)),
                ('price', models.CharField(max_length=42)),
                ('cost', models.CharField(max_length=42)),
                ('category', models.CharField(max_length=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
